"""Tests for the DIGIPIN encode / decode / validate module.

The reference vectors below were generated by running the verbatim port of
the official India Post Apache-2.0 algorithm at github.com/INDIAPOST-gov/digipin
against well-known landmark coordinates. Round-trip accuracy is bounded by the
~3.8 m level-10 cell, so we assert decode → encode is exact and that the
recovered lat/lng is within 5 m of the input.
"""
from __future__ import annotations

import random
import socket

import pytest

from bharataddress import parse
from bharataddress.digipin import (
    MAX_LAT,
    MAX_LON,
    MIN_LAT,
    MIN_LON,
    decode,
    encode,
    validate,
)

# (label, lat, lng, expected_digipin)
REFERENCE_POINTS = [
    ("Delhi India Gate",       28.6129, 77.2295, "39J-429-L4TK"),
    ("Mumbai CST",             18.9398, 72.8355, "4FK-PC2-K97F"),
    ("Bangalore Vidhana",      12.9794, 77.5912, "4P3-JJT-4KL7"),
    ("Chennai Marina",         13.0500, 80.2824, "4T3-8MM-4639"),
    ("Kolkata Howrah Bridge",  22.5851, 88.3468, "2TF-J96-LFFT"),
]


@pytest.mark.parametrize("label,lat,lng,expected", REFERENCE_POINTS, ids=[p[0] for p in REFERENCE_POINTS])
def test_encode_reference_points(label, lat, lng, expected):
    assert encode(lat, lng) == expected


@pytest.mark.parametrize("label,lat,lng,expected", REFERENCE_POINTS, ids=[p[0] for p in REFERENCE_POINTS])
def test_decode_recovers_within_cell(label, lat, lng, expected):
    rlat, rlng = decode(expected)
    # Level-10 cell is ~3.8 m on a side; centre should be within ~5 m of input.
    assert abs(rlat - lat) * 111_000 < 5
    assert abs(rlng - lng) * 100_000 < 5


def test_format_shape():
    code = encode(28.6129, 77.2295)
    assert len(code) == 12
    assert code[3] == "-" and code[7] == "-"
    parts = code.split("-")
    assert [len(p) for p in parts] == [3, 3, 4]


def test_decode_accepts_with_or_without_dashes():
    code = encode(12.9794, 77.5912)
    lat1, lng1 = decode(code)
    lat2, lng2 = decode(code.replace("-", ""))
    assert (lat1, lng1) == (lat2, lng2)


def test_decode_is_case_insensitive():
    code = encode(22.5851, 88.3468)
    assert decode(code.lower()) == decode(code)


def test_roundtrip_random():
    rng = random.Random(42)
    for _ in range(500):
        lat = rng.uniform(MIN_LAT + 0.01, MAX_LAT - 0.01)
        lng = rng.uniform(MIN_LON + 0.01, MAX_LON - 0.01)
        code = encode(lat, lng)
        rlat, rlng = decode(code)
        # Re-encoding the centre must yield the same code (cell is closed under round-trip).
        assert encode(rlat, rlng) == code


@pytest.mark.parametrize(
    "lat,lng",
    [
        (0.0, 77.0),       # below min lat
        (40.0, 77.0),      # above max lat
        (28.0, 50.0),      # below min lon
        (28.0, 120.0),     # above max lon
        (-12.0, 80.0),
    ],
)
def test_encode_rejects_out_of_bounds(lat, lng):
    with pytest.raises(ValueError):
        encode(lat, lng)


@pytest.mark.parametrize(
    "bad",
    [
        "",
        "39J-429-L4T",     # too short
        "39J-429-L4TKK",   # too long
        "AAA-BBB-CCCC",    # invalid characters
        "39J-429-L4T1",    # 1 is not in alphabet
        "39J-429-L4T0",    # 0 is not in alphabet
    ],
)
def test_validate_rejects_bad(bad):
    assert validate(bad) is False
    with pytest.raises(ValueError):
        decode(bad)


def test_validate_rejects_non_string():
    assert validate(None) is False  # type: ignore[arg-type]
    assert validate(12345) is False  # type: ignore[arg-type]


def test_validate_accepts_good():
    assert validate("39J-429-L4TK") is True
    assert validate("39J429L4TK") is True


def test_parse_accepts_latlng_hint():
    addr = "Plot 88, Basheer Bagh, Hyderabad 500001"
    result = parse(addr, latlng=(17.3850, 78.4867))
    assert result.digipin is not None
    # Round-trip the populated digipin and confirm it lands inside Hyderabad.
    rlat, rlng = decode(result.digipin)
    assert 17.0 < rlat < 18.0
    assert 78.0 < rlng < 79.0


def test_parse_default_digipin_auto_populated_from_centroid():
    """Since v0.2.2 pincodes.json carries centroids, parse() auto-fills digipin
    for any input whose pincode resolves to a record with latitude/longitude."""
    result = parse("Plot 88, Basheer Bagh, Hyderabad 500001")
    assert result.digipin is not None
    assert len(result.digipin.replace("-", "")) == 10


def test_parse_digipin_none_for_unknown_pincode():
    result = parse("some random text with no pincode")
    assert result.digipin is None


def test_no_network_during_digipin():
    """Architectural constraint: digipin functions never touch the network."""
    real_socket = socket.socket

    def _blocked(*a, **kw):
        raise AssertionError("digipin attempted a network call")

    socket.socket = _blocked  # type: ignore[assignment]
    try:
        code = encode(28.6129, 77.2295)
        decode(code)
        validate(code)
    finally:
        socket.socket = real_socket  # type: ignore[assignment]
